[project]
name = "chainlit-azure-blob"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "azure-storage-blob>=12.24.0,<13",
]

[tool.uv.sources]
pytest-chainlit = { workspace = true }

[dependency-groups]
dev = [
    "azure-identity>=1.14.1,<2",
    "pytest-chainlit",
    "pytest-mock>=3.14.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
