[project]
name = "chainlit-dynamodb"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "aiohttp>=3.11.10",
    "boto3>=1.34.73,<2",
]

[dependency-groups]
dev = [
    "pytest-chainlit",
]

[tool.uv.sources]
pytest-chainlit = { workspace = true }

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
