[project]
name = "chainlit-s3"
version = "0.1.0"
description = "Amazon S3 storage client for use with Chainlit."
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "boto3>=1.34.73,<2",
]

[dependency-groups]
dev = [
    "moto>=5.0.22",
    "pytest-chainlit",
    "types-boto3-dynamodb>=1.35.74",
]

[tool.uv.sources]
pytest-chainlit = { workspace = true }

[build-system]
requires = ["hatchling", "hatch-regex-commit"]
build-backend = "hatchling.build"

[tool.hatch.version]
source = "regex_commit"
path = "src/chainlit_sqlalchemy/__init__.py"
pattern = '^__version__ = "(.+)"$'
commit_message = "chore(sqlalchemy): bump version {current_version} → {new_version}"
tag_name = "sqlalchemy/v{new_version}"
