[project]
name = "chainlit-sqlalchemy"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = []

[project.optional-dependencies]
azure = [
  "chainlit-azure",
]
s3 = [
  "chainlit-s3",
]

[tool.uv.sources]
chainlit-azure = { workspace = true }
chainlit-s3 = { workspace = true }
