[project]
name = "chainlit-sqlalchemy"
version = "0.1.0"
description = "SQLAlchemy data layer for Chainlit."
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "aiohttp>=3.11.10",
    "sqlalchemy[asyncio]>=2.0.28,<3",
]

[project.optional-dependencies]
postgres = [
    "asyncpg>=0.29.0",
    "psycopg2-binary>=2.9.9"
]
sqlite = [
    "aiosqlite>=0.20.0"
]
azure = [
    "chainlit-azure",
]
azure-blob = [
    "chainlit-azure-blob",
]
gcs = [
    "chainlit-gcs",
]
s3 = [
    "chainlit-s3",
]

[dependency-groups]
dev = [
    "aiosqlite>=0.20.0",
    "pytest-chainlit",
]

[tool.uv.sources]
chainlit-azure = { workspace = true }
chainlit-azure-blob = { workspace = true }
chainlit-gcs = { workspace = true }
chainlit-s3 = { workspace = true }
pytest-chainlit = { workspace = true }

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
